language: php

php:
    - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer install

script:
   - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
